apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: my-container
    image: nginx
    command: ["sleep", "3600"]  # Running a sleep command to keep the container running
  tolerations:
      - key: "prod"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
