kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["pods","deployments","services"]
    verbs: ["get","apply","delete","watch","create","patch"]

