kind: Pod
apiVersion: v1
metadata:
  name: sidecar-container

spec:
  containers:
    - name: main-container
      image: busybox:latest
      command: ["sh","-c", "while true; do echo 'Hello Guys' >> /var/log/app.log; sleep 5; done"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log

    - name: sidecar-container
      image: busybox:latest
      command: ["sh", "-c", "tail -f /var/log/app.log" ]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log
  volumes:
    - name: shared-logs
      emptyDir: {} 
