apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-4
  name: sample-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-4
    spec:
      containers:
      - image: devopsprosamples/next-path-sample-4
        name: next-path-sample-4
        resources: {}
status: {}
