apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-1
  name: sample-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-1
    spec:
      containers:
      - image: devopsprosamples/next-path-sample-1
        name: next-path-sample-1
        resources: {}
status: {}
