# 2)Docker-registry Secret: declare as Environment variable
# kubectl create secret docker-registry docker-secret --docker-email=example@gmail.com --docker-username=dev --docker-password=pass1234 --docker-server=my-registry.example:5000
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-2
spec:
  containers:
  - name: demo-container
    image: nginx
    envFrom:
    - secretRef:
       name: docker-secret

# kubectl get pods
# kubectl exec secret-demo-2 -it -- /bin/bash
# e env | grep .dockerconfigjson
# o/p->.dockerconfigjson={"auths":{"my-registry.example:5000":{"username":"dev","password":"pass1234","email":"example@gmail.com","auth":"ZGV2OnBhc3MxMjM0"}}}
