apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo-pod
spec:
  containers:
    - name: app
      image: busybox
      command: [ "sh", "-c", "echo 'Dynamic PVC Working!' > /data/test.txt && sleep 3600" ]
      volumeMounts:
        - name: storage
          mountPath: /data
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: my-dynamic-pvc
