apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP     # ClusterIP service type
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80         # service port
    targetPort: 80   # Containers port



# Kubectl apply -f cluster-ip.yml
# kubectl get svc
# kubectl port-forward service/demoservice 5000:80
# or
# minikube service nginx-clusterip --url