#The Headless Service YAML file defines a Kubernetes Service that does not assign an IP address to the pods. 
#It is used for discovering and connecting to individual pods directly.
apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: web
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
