apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer   # LoadBalancer service type
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80          # service port
      targetPort: 80    # Containers port

# kubectl apply -f load-balancer.yaml
# kubectl get pods
# kubectl get svc

# Access the Application Since Minikube does not support external LoadBalancer services natively, use the following command to access it:
# minikube service my-app-service --url