apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-3
  name: sample-3
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sample-3
  type: ClusterIP
status:
  loadBalancer: {}
