apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-1
  name: sample-1
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sample-1
  type: ClusterIP
status:
  loadBalancer: {}
