kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: testpod                  
spec: 
  schedulerName: my-scheduler                             
  containers:                      
    - name: c00                     
      image: ubuntu              
      command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]
  restartPolicy: Never