apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]



  
# Scenarions:-------------------------------------------------
# Role           |   Cluster role   |   Cluster role
#  |             |         |        |        |
# Role binding   |   Role binding   |   Cluster role binding
# ------------------------------------------------------------