---
kind: Pod
apiVersion: v1
metadata:
  name: nodelabels
  labels:
    env: development
spec:
    containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]
    nodeSelector:         #add nodeSelector operator and key:value                                
       hardware: t2-medium

--- 
     
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    myname: ganesh
  name: test
spec:
  nodeSelector:          #add nodeSelector operator and key:value
    myname: ganesh
  containers:
  - image: nginx
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

---