# 3)TLS Secret: declare as volume file
# make two files: serverca.crt and servercakey.pem
# kubectl create secret tls my-tls-secret --cert=/home/ganesh/kubernetes/8.Secret/serverca.crt --key=/home/ganesh/kubernetes/8.Secret/servercakey.pem
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-3
spec:
  containers:
  - name: demo-container
    image: nginx
    volumeMounts:
      - name: data
        mountPath: /etc/cert-data
  volumes:
  - name: data
    secret:
      secretName: my-tls-secret