#Communication between two containers within same pod in same node:
kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]
    - name: c01
      image: httpd
      ports:
       - containerPort: 80


# kubectl exec testpod -it -c c00 -- /bin/bash  //to enter in container
# apt update && apt install curl -y
# curl localhost:80      